#pragma once
#include <thread>
#include <string>
#include "iostream"
#include <cmath>
#include <math.h>
#include <vector>
#include <cstring>
#include <windows.h>
#include <psapi.h>
#include <dwmapi.h>
#include <chrono>
#include <thread>
#include <string_view>
#include <fstream>
#include <algorithm>
#include <TlHelp32.h>